version: "3.7"
services:
  web_flask:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
      args:
        project_directory: "/projects/"
    ports:
      - "5000:5000"
    volumes:
      - ".:/projects"
    environment:
      TZ: "Asia/Tokyo"
      # Flaskのホットリロード設定
      FLASK_APP: "app/main.py"
      FLASK_ENV: "development"
    command: "flask run --host 0.0.0.0 --port 5000"